### ISSUE TITLE
Reading a firmware image?

### ISSUE THREAD

**Issue by ghost** [ghaststeam/MagicEMX#20]
I downloaded the pre-release version of this program from the release section (which says it tries to load a firmware image) and was wondering how you get the program to do that? When you select the 'file' section and select the 'load bios/firmware image' it brings up the dialog but when you try any file it either crashes/closes unexpectedly or shows an error message that just says "FAILED". Do you need to use only the actual PS4 bios (I have a PS4, by the way) to do this and will it really work, or what kind of firmware image exactly works?

**Comment by PackSciences** [comment]
You are talking with yourself, maybe you need to see a doctor
