### ISSUE TITLE
gitter /freenode-irc  ?

### ISSUE THREAD

**Issue by necrose99** [ghaststeam/MagicEMX#29]
https://gitter.im/#apps-panel

if you have a linux port (O/S on BSD is closer and has some kernel lib support on linux , so may be easier to > linux libs, mac os is likely the closer , but travis-ci or jenkins-ci can do some tests/releases automation.

**Comment by Embrendassy** [comment]
I have considered Travis CI for later on, but at this point in time I'm not going to implement it until the project is further along and reaches an alpha 0.2 at least, which, by then, everything should be cleaned up and improved.

**Comment by ghaststeam** [comment]
Thanks for letting me know! Build automation will likely be added sometime in the near future.

**Comment by vgturtle127** [comment]
@ghaststeam Can we close this until the project is much further along?

**Comment by necrose99** [comment]
A number of projects use free node irc.
For chat , for build triggers etc. , 
And for sub-rooms , ie Sabayon Linux,  -dev , -social,  -infra for build spam ...  but having irc to free node module,  could be a very nice to have.

**Comment by vgturtle127** [comment]
@necrose99 True as that may be, we barely have any code written, and some of the stuff we do have written is placeholder and null stuff. We can keep things just on this GItHub for now, we want to keep it more on the down low anyway, die to some of the backlash and what not from PS4EMX.

**Comment by necrose99** [comment]
i just would like to get running ebuild or
 curious if thiers a makefile , as I could use emake....  , for now I can use debian files ,  in ebuild and wrap. 
api will unpack.  
(https://github.com/fusion809/sabayon-tools/blob/master/x11-wm/moksha-bin/moksha-bin-0.1.0.ebuild exemplar) 

however emake (make sandbox wrapper) install  , on a make file will build and install ... from sources (Preferred) 

nodejs other than net-libs/nodejs , NPM is tolerated to a point , was a move to to autogen ebuilds... 

anyhow , I'll have to look up means of building from sources.

**Comment by vgturtle127** [comment]
@necrose99 I think you are misunderstanding. Haha. That's what I'm saying. There isn't anything to compile, and if you did get a binary, it wouldn't run anything. Like, literally anything. We have some very basic stuff emulated, and a raw framework, but the rest is ideas and planning and null values.

**Comment by necrose99** [comment]
by "compile a binary/usable...  " i just mean NPM will build it. ,  gentoo 9999 ebuilds means it git clones, builds from scratch. 
for now I can dump debian's into fs .in ebuild deb_unpack.  (Gentoo devs do this (last resort) but tend to frown on it) 
but from source gets more smiles... from devs on high ,   also isnt ARCH locked.  ie Banna-pi etc...  
however getting NPM packages to build via gentoo ebuilds  is a pest as a lowly admin user. 
building packages against npm is terribly under documented atm.  

since I meddle with docker etc , its terribly handy to have. , so meddling an ebuild would be a a item to cross off my repo's Done list.  , I'll take any tips..

**Comment by MoochMcGee** [comment]
This project is a scam, don't waste your time.
