### ISSUE TITLE
Specifications PS4 GPU 

### ISSUE THREAD

**Issue by Altaiar** [ghaststeam/MagicEMX#30]
GPU See Picute
http://s3.picofile.com/file/8197954192/Capture.PNG

**Comment by ghaststeam** [comment]
Thanks for the info. I'm currently thinking of the best way to start seriously emulating the GPU.

**Comment by vgturtle127** [comment]
@ghaststeam There is much more publicly available information now, can we close this? This would be way better on the Wiki.
