### ISSUE TITLE
please launch stable release version with cheat and cheat search ?

### ISSUE THREAD

**Issue by rpgcollectors** [ghaststeam/MagicEMX#32]
up

sorry for my bad english my french origin

**Comment by ghaststeam** [comment]
Sorry, but there won't be stable releases for a long time. Some real alphas will eventually happen.

I'm going to make options that allow various cheat potentials though, but not until things improve overall.

**Comment by rpgcollectors** [comment]
ah ok well I count on you to do a very good emulator as well or even better than pcsx2

**Comment by vgturtle127** [comment]
@ghaststeam Please close this.
