### ISSUE TITLE
If this project is still under development please let us know its process.

### ISSUE THREAD

**Issue by send2siyad** [ghaststeam/MagicEMX#35]
I appreciate ghaststeam as you are the only one has shown the guts to think ps4 emulation.But you should seriously consider updating read me file and share your progress.

**Comment by vgturtle127** [comment]
@send2siyad The project is not far enough along to show any progress, nothing runs and we are just getting a framework of general emulation core features down.

@ghaststeam Please close this.

**Comment by ghaststeam** [comment]
Project is pretty much dead. I have no time anymore to even think of doing hardware tests or any kind of other stuff I was thinking of doing (such as disc reading and furthering the GPU emulation).

If anyone wants to take this further for now, just send a pull request or ask any questions you may have.

I, personally, don't have the time to contribute anymore to this project in the foreseeable future.
