### ISSUE TITLE
Its 2017,is this project still alive?

### ISSUE THREAD

**Issue by Bullshirt** [ghaststeam/MagicEMX#36]
Its 2017,is this project still alive,does it work and is there any help you need(if its alive)?

**Comment by ghaststeam** [comment]
I've pretty much given up at this point. If anyone else wants to continue on, be my guest and send a pull request. If someone else really believes some hardware tests/etc. can take this to the next step (i.e., a full-interpreter or more in-depth GPU emulation along with the other tidbits), I can transfer this account to them. As of now I have nothing to personally add, but welcome anyone willing to help in any way.
